from datetime import date
from typing import Protocol, runtime_checkable

from repaso.config.settings import Settings
from repaso.schemas.common import (
    CompetencyId,
    EscalationId,
    FamilyId,
    ItemId,
    MaterialId,
    SessionId,
    StudentId,
)
from repaso.schemas.enrollment import EnrollmentProgress
from repaso.schemas.escalation import Escalation
from repaso.schemas.family import Family
from repaso.schemas.item import Item, ItemStatus
from repaso.schemas.mastery import MasteryState
from repaso.schemas.material import Material
from repaso.schemas.operation import OperationRecord
from repaso.schemas.review import QuarantineItem
from repaso.schemas.schedule import ExamDate, SpacedItemState
from repaso.schemas.session import PracticeSession
from repaso.schemas.student import Student


@runtime_checkable
class StateStore(Protocol):
    def put_family(self, family: Family) -> None: ...
    def get_family(self, family_id: FamilyId) -> Family | None: ...
    def find_family_by_chat(self, channel: str, chat_ref: str) -> Family | None: ...
    def list_families(self) -> list[Family]: ...
    def forget_family(self, family_id: FamilyId) -> None: ...
    def put_student(self, student: Student) -> None: ...
    def get_student(self, student_id: StudentId) -> Student | None: ...
    def list_students(self, family_id: FamilyId) -> list[Student]: ...
    def put_mastery(self, state: MasteryState) -> None: ...
    def get_mastery(
        self, student_id: StudentId, competency_id: CompetencyId
    ) -> MasteryState | None: ...
    def list_mastery(self, student_id: StudentId) -> list[MasteryState]: ...
    def put_spaced(self, state: SpacedItemState) -> None: ...
    def list_spaced(self, student_id: StudentId) -> list[SpacedItemState]: ...
    def put_exam_date(self, exam: ExamDate) -> None: ...
    def list_exam_dates(self, student_id: StudentId) -> list[ExamDate]: ...
    def delete_exam_date(self, student_id: StudentId, exam_date: date) -> None: ...
    def put_item(self, item: Item) -> None: ...
    def list_family_items(self, family_id: str) -> list[Item]: ...
    def get_item(self, item_id: ItemId) -> Item | None: ...
    def list_items_by_competency(
        self, competency_id: CompetencyId, status: ItemStatus | None = None
    ) -> list[Item]: ...
    def put_material(self, material: Material) -> None: ...
    def get_material(self, material_id: MaterialId) -> Material | None: ...
    def put_session(self, session: PracticeSession) -> None: ...
    def get_session(self, session_id: SessionId) -> PracticeSession | None: ...
    def get_session_by_date(
        self, student_id: StudentId, session_date: date
    ) -> PracticeSession | None: ...
    def put_escalation(self, escalation: Escalation) -> None: ...
    def list_escalations(self, family_id: FamilyId) -> list[Escalation]: ...
    def get_escalation(self, escalation_id: EscalationId) -> Escalation | None: ...
    def list_pending_escalations(self, family_id: FamilyId) -> list[Escalation]: ...
    def put_quarantine(self, item: QuarantineItem) -> None: ...
    def get_quarantine(self, family_id: FamilyId, quarantine_id: str) -> QuarantineItem | None: ...
    def list_pending_quarantine(self, family_id: FamilyId) -> list[QuarantineItem]: ...
    def put_enrollment(self, progress: EnrollmentProgress) -> None: ...
    def get_enrollment(self, channel: str, chat_ref: str) -> EnrollmentProgress | None: ...
    def delete_enrollment(self, channel: str, chat_ref: str) -> None: ...
    def claim(self, key: str, owner: str) -> bool: ...
    def release_claim(self, key: str, owner: str) -> None: ...
    def put_record(self, record: OperationRecord) -> None: ...
    def get_record(self, scope: str, key: str) -> OperationRecord | None: ...
    def list_records(self, scope: str, prefix: str = "") -> list[OperationRecord]: ...
    def delete_records(self, scope: str) -> None: ...
    def acquire_lease(self, scope: str, owner: str, expires: float) -> bool: ...
    def release_lease(self, scope: str, owner: str) -> None: ...
    def reserve_budget(self, scope: str, day: str, limit: int, global_limit: int) -> bool: ...
    def list_materials(self, family_id: str) -> list[Material]: ...
    def list_sessions(self, student_id: str) -> list[PracticeSession]: ...
    def list_quarantine(self, family_id: str) -> list[QuarantineItem]: ...
    def apply_outcome(
        self,
        key: str,
        mastery: MasteryState,
        spaced: SpacedItemState,
        previous: MasteryState | None,
    ) -> bool: ...


def build_state_store(settings: Settings) -> StateStore:
    if settings.local_mode:
        from repaso.tools.state_local import LocalStateStore

        return LocalStateStore(settings.local_data_dir / "state")
    from repaso.tools.state_dynamo import DynamoStateStore

    return DynamoStateStore(settings.ddb_table)
